config/routes.rb
Rails.application.routes.draw do

   root 'home#home'
   get 'home/search'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :keywords 
	self.primary_key = 'geoname_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'rest-client'
	def home
	end

	def search
		@responseObjs = Place.includes(:keywords).where("lower(keywords.name) LIKE ?", "%#{params[:search].downcase}%").references(:keywords)
		if @responseObjs.blank?
			responseJson = RestClient.get 'http://api.geonames.org/searchJSON',  {:params => {q: params[:search], username: :demo, style: :full, maxRows: 10}}
			@responseObjs = JSON.parse(responseJson)["geonames"]
			unless @responseObjs.blank?
				@responseObjs.each do |obj|
					placeobj = Place.find_or_create_by(name: obj["name"], country_name:obj["countryName"], lat:obj["lat"], lng:obj["lng"],  population:obj["population"], geoname_id: obj["geonameId"], elevation: obj["elevation"] )
					placeobj.keywords.create(name: params[:search])
				end
			else
				@responseErr = JSON.parse(responseJson)["status"]["message"]		
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search_result.html.erb
<tr>
	<td><%= result["geoname_id"] || result["geonameId"]%></td>
  <td><%= result["country_name"] || result["countryName"]%></td>
  <td><%= result["lat"] %></td>
  <td><%= result["lng"] %></td>
  <td><%= result["name"] %></td>
	<td><%= result["population"] %></td>
	<td><%= result["elevation"] %></td>
</tr>

app/views/home/home.html.erb
<div class="row">
  <div class="col-md-12">&nbsp;</div>
</div>
<div class="row">
  <div class="col-md-12">&nbsp;</div>
</div>
<div class="row">
  <div class="col-md-12"></div>
</div>
<div class="row">
	<div class="col-md-3"></div>
  <div class="col-md-6">
		<%= form_tag(home_search_path, :method => "get", remote: true ,id: "search-form" , class: "form-inline") do %>
			<div class="form-group">
			 	<%= label_tag('search','Where do you want to go?' , class: "control-label") %>
				<%= text_field_tag :search, "", placeholder: "Search palce" , class: "form-control" , "aria-describedby": "helpBlock"%>
				<%= submit_tag "Search",  class: "btn btn-default" %>
				<span id="helpBlock" class="help-block">Search any place with the help of GeoNames api</span>
			</div>			
		<% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>
<div class="row">
  <div class="col-md-12">
	<div id="search_result">
	</div>  	
  </div>
</div>

app/views/home/search.js.erb
<% if @responseErr.blank? %>
	$('#search_result').html("<table id='result_table' class='table table-hover'><tr><th>Geoname Id</th><th>CountryName</th><th>Lat</th><th>Long</th><th>Name</th><th>Population</td><th>Elevation</td></tr><%= escape_javascript(render partial: 'home/search_result', collection: @responseObjs, as: :result) %></table>");
<% else %>
	$('#search_result').html('');
	alert('<%= @responseErr %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Demoapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Demoapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>        
      </div><!--/row-->

      <footer>
        <center><p>demoapp&copy; Company 2016</p></center>
      </footer>

    </div> <!-- /container -->

  </body>
</html>